# Generated by Django 4.2.1 on 2023-05-23 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_reservation_delete_reservations'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('itme_description', models.TextField()),
                ('item_price', models.FloatField()),
                ('item_img', models.URLField()),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='page.category')),
            ],
        ),
    ]
